### PR TITLE
Added debug, updated app descriptor, added load-config element.

### PR DESCRIPTION
**Pull request by horixon**
Changes I made to the ant task for are builds.  Feel free to pull them in if you like...
1. Added attribute for debug to compile the tests in debug for Actionscript Code Coverage (http://labs.adobe.com/technologies/ascode_coverage/).
2. Updated the flexUnitDescriptor.template changing <version> to <versionNumber> so it works with AIR 2.5
3. Added an load-config element to externalize compiler config.  Currently it only handles one <load-config> element but could support more if they were pushed an array or similar.

Thanks
Justin Wagle.

Sample usage:

<flexunit
                player="@{player}"
                toDir="@{to-dir}/"
                haltonfailure="false"
                verbose="false"
                localTrusted="true"
                headless="false"
                debug="true">

```
            <load-config filename="@{additional-compiler-config}"/>

            <source dir="@{source-dir}"/>
            <testSource dir="@{test-dir-source}">
                <include name="**/*Test.as"/>
            </testSource>               

        </flexunit>
```

### CODE REVIEW

**Comment by blegros** [comment]
Thanks for the contribution guys!  I will work on getting this into 4.2 since 4.1 is relatively close to release and in an RC state.  Hadn't used DynamicElement before so it's cool to see another impl.  In my 4.2 branch I have support for multiple flex configs, but I like how you've broken up Compilation a bit, so I'll try to merge our two impls.  Thanks for the help!

-Brian

**Comment by horixon** [comment]
No problem thanks for all your work!  I was trying to make the load-config API similar to mxmlc.  I am thinking of adding support for multiple load-config elements and for the append attribute on the load-config element.  I haven't had time yet.

I can keep moving forward on that in my fork or wait if you merge up.  What are your thoughts?  What is your time frame for 4.2?

Also to note the changes to the AIR app descriptor xml with the change of <version> to <versionNumber> is not backward compatible:(  So may need a clean way to switch back and forth depending on air version...

**Comment by blegros** [comment]
The timeframe for each FlexUnit 4 release is about 6 months.  You're always welcome to add features on your own and submit pull requests; that's totally cool with us.  With respect to the ADL descriptor, I've tokenized the template for the descriptor, so we should be able to do the same for the <versionNumber> or <version> attribute.  HTH.

**Comment by blegros** [comment]
The timeframe for each FlexUnit 4 release is about 6 months.  You're always welcome to add features on your own and submit pull requests; that's totally cool with us.  With respect to the ADL descriptor, I've tokenized the template for the descriptor, so we should be able to do the same for the <versionNumber> or <version> attribute.  HTH.

**Pull request merged**
